name: List Available AI Models

on:
  workflow_dispatch:
    inputs:
      output_format:
        description: 'Output format for the models list'
        required: false
        default: 'detailed'
        type: choice
        options:
          - 'detailed'
          - 'ids_only'
          - 'json'

permissions:
  models: read

jobs:
  list-models:
    runs-on: ubuntu-latest
    steps:
      - name: List Available Models
        id: list-models
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FORMAT: ${{ github.event.inputs.output_format }}
        run: |
          echo "=========================================="
          echo "DEBUG: Listing available models from GitHub Models API"
          echo "Output format: $OUTPUT_FORMAT"
          echo "=========================================="
          
          echo "DEBUG: Making API request to list models..."
          MODELS_RESPONSE=$(curl -L "https://models.github.ai/catalog/models" \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28")
          
          echo "DEBUG: Models API response received"

          if [ "$OUTPUT_FORMAT" = "json" ]; then
            echo "=========================================="
            echo "Available Models (JSON format):"
            echo "=========================================="
            echo "$MODELS_RESPONSE" | jq '.'
          elif [ "$OUTPUT_FORMAT" = "ids_only" ]; then
            echo "=========================================="
            echo "Available Model IDs:"
            echo "=========================================="
            echo "$MODELS_RESPONSE" | jq -r '.[] | .id'
          else
            echo "=========================================="
            echo "Available Models (Detailed):"
            echo "=========================================="
            echo "$MODELS_RESPONSE" | jq -r '.[] | "ID: \(.id)\nName: \(.name // "N/A")\nDescription: \(.description // "N/A")\n---"'
          fi
          
          echo "=========================================="
          echo "Total models found: $(echo "$MODELS_RESPONSE" | jq 'length')"
          echo "=========================================="

      - name: Save models list as artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Saving models list to artifact..."
          curl -L "https://models.github.ai/catalog/models" \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" > /tmp/models_list.json
             
      - name: Upload models list artifact
        uses: actions/upload-artifact@v4
        with:
          name: available-models-${{ github.run_number }}
          path: /tmp/models_list.json
